=== modicio/modicio/src/main/resources/modicio_lang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://modic.io/ns"
           xmlns="http://modic.io/ns"
           xmlns:mio="http://modic.io/ns"
           elementFormDefault="qualified">

    <!-- Root Model Definition -->

    <xs:element name="Fragment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Node" type="Node" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Instance" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Header" type="Header"/>
                            <xs:element name="Object" type="Object" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="modelRoot" type="mio:mID" use="required" />
                        <!-- uri of an instance must be globally unique -->
                        <xs:attribute name="uri" type="mio:mID" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="Trace" type="Trace" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="predecessor_id" type="xs:dateTime"/>
            <xs:attribute name="is_open" type="xs:boolean" use="required"/>
            <xs:attribute name="variant_name" type="xs:string" use="required"/>
            <xs:attribute name="running_time" type="xs:dateTime" use="required"/>
            <xs:attribute name="running_id" type="xs:string" use="required"/>
            <xs:attribute name="is_reference" type="xs:boolean" use="required"/>
            <xs:attribute name="global_id" type="xs:string"/>
            <xs:attribute name="variant_id" type="xs:string" use="required"/>
            <xs:attribute name="variant_time" type="xs:dateTime" use="required"/>
        </xs:complexType>

        <!-- Global Value & Reference Constraints -->

        <xs:key name="InstantiableNode">
            <xs:selector xpath=".//mio:Node" />
            <xs:field xpath="@uri" />
        </xs:key>

        <xs:key name="ReferenceableInstance">
            <xs:selector xpath=".//mio:Instance|.//mio:CompositionInstance" />
            <xs:field xpath="@uri" />
        </xs:key>

        <xs:key name="InstantiableAttribute">
            <xs:selector xpath=".//mio:Attribute" />
            <xs:field xpath="@uri" />
        </xs:key>

        <xs:keyref name="InstanceOfReference" refer="InstantiableNode">
            <xs:selector xpath=".//mio:Object" />
            <xs:field xpath="@instanceOf" />
        </xs:keyref>

        <xs:keyref name="HeaderObjectReference" refer="ReferenceableInstance">
            <xs:selector xpath=".//mio:Header" />
            <xs:field xpath="@compositeInstanceUri" />
        </xs:keyref>

        <xs:keyref name="HeaderNodeReference" refer="InstantiableNode">
            <xs:selector xpath=".//mio:Header" />
            <xs:field xpath="@compositeNodeUri" />
        </xs:keyref>

        <xs:keyref name="InstanceOfAttribute" refer="InstantiableAttribute">
            <xs:selector xpath=".//mio:AttributeInstance" />
            <xs:field xpath="@attributeUri" />
        </xs:keyref>

        <xs:keyref name="ChildOfReference" refer="InstantiableNode">
            <xs:selector xpath=".//mio:ParentRelation" />
            <xs:field xpath="@target" />
        </xs:keyref>

        <xs:keyref name="CompositionTargetReference" refer="InstantiableNode">
            <xs:selector xpath=".//mio:Composition" />
            <xs:field xpath="@target" />
        </xs:keyref>

        <xs:keyref name="ModelRootReference" refer="InstantiableNode">
            <xs:selector xpath=".//mio:Instance|.//mio:CompositionInstance" />
            <xs:field xpath="@modelRoot" />
        </xs:keyref>

        <xs:unique name="UniqueNodeName">
            <xs:selector xpath="./mio:Model/*" />
            <xs:field xpath="@name" />
        </xs:unique>

        <xs:unique name="UniqueURI">
            <xs:selector xpath=".//*" />
            <xs:field xpath="@uri" />
        </xs:unique>

    </xs:element>

    <xs:simpleType name="mID">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="modicio:.*" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Reference Type Definitions-->

    <!-- Metamodel -->

    <xs:complexType name="Node">
        <xs:sequence>
            <xs:element name="Annotation" type="Annotation"/>

            <!-- Attribute -->
            <xs:element name="Attribute" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="uri" type="mio:mID" use="required"/>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="dType" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>

            <!-- Association Relation -->
            <xs:element name="AssociationRelation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Interface" type="mio:Interface"/>
                    </xs:sequence>
                    <xs:attribute name="uri" type="mio:mID" use="required"/>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="target" type="mio:mID" use="required"/>
                </xs:complexType>
            </xs:element>

            <!-- Parent Relation -->
            <xs:element name="ParentRelation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="uri" type="mio:mID" use="required"/>
                </xs:complexType>
            </xs:element>

            <!-- Plugin -->
            <xs:element name="Plugin" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="description" type="xs:string" use="required"/>
                    <xs:attribute name="resolver" type="xs:string" use="required"/>
                    <xs:attribute name="content" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>

            <!-- Concretization -->
            <xs:element name="Concretization" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="AttributeInstance" type="AttributeInstance" minOccurs="0"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>

            <!-- Composition -->
            <xs:element name="Composition" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="uri" type="mio:mID" use="required"/>
                    <xs:attribute name="role" type="xs:string" use="required"/>
                    <xs:attribute name="target" type="mio:mID" use="required"/>
                    <xs:attribute name="public" type="xs:boolean" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="Script" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="any_value" type="xs:string"/>
                    </xs:all>
                    <xs:attribute name="uri" type="mio:mID" use="required"/>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="action_type" type="xs:string" use="required"/>
                    <xs:attribute name="resolver" type="mio:mID" use="required"/>
                </xs:complexType>
            </xs:element>

        </xs:sequence>

        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="uri" type="mio:mID" use="required"/>
        <xs:attribute name="is_abstract" type="xs:boolean" use="required"/>

    </xs:complexType>

    <xs:complexType name="Annotation">
        <xs:attribute name="version_time" type="xs:dateTime"/>
        <xs:attribute name="version_id" type="xs:string"/>
        <xs:attribute name="variant_time" type="xs:dateTime"/>
        <xs:attribute name="variant_id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Trace">
        <xs:sequence>
            <xs:element name="Delta" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="content" type="xs:string"/>
                    <xs:attribute name="target" type="mio:mID"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Interface">
        <xs:sequence>
            <xs:element name="LeftOpen" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="border_version_time" type="xs:dateTime" use="required"/>
                    <xs:attribute name="border_version_id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="RightOpen" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="border_version_time" type="xs:dateTime" use="required"/>
                    <xs:attribute name="border_version_id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Region" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="left_border_version_time" type="xs:dateTime" use="required"/>
                    <xs:attribute name="left_border_version_id" type="xs:string"/>
                    <xs:attribute name="right_border_version_time" type="xs:dateTime" use="required"/>
                    <xs:attribute name="right_border_version_id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Point" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="variant_time" type="xs:dateTime" use="required"/>
                    <xs:attribute name="variant_id" type="xs:string"/>
                    <xs:attribute name="version_time" type="xs:dateTime"/>
                    <xs:attribute name="version_id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <!-- Instance -->

    <xs:complexType name="Object">
        <xs:sequence>

            <xs:element name="AttributeInstance" type="AttributeInstance" minOccurs="0" maxOccurs="unbounded"/>

            <xs:element name="AssociationInstance" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="instance_uri" type="mio:mID" use="required"/>
                    <xs:attribute name="association_uri" type="mio:mID" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="CompositionInstance" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Object" type="Object" maxOccurs="unbounded"/>
                    </xs:sequence>

                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="model_root" type="mio:mID" use="required" />
                    <!-- uri of an instance must be globally unique -->
                    <xs:attribute name="uri" type="mio:mID" use="required" />

                    <xs:attribute name="composition_uri" type="mio:mID" use="required"/>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="instanceOf" type="mio:mID" use="required" />
    </xs:complexType>

    <xs:complexType name="Header">
        <xs:sequence>
            <xs:element name="HeaderElement" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="composite_node_uri" type="mio:mID"/>
                        <xs:element name="composite_instance_uri" type="mio:mID"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AttributeInstance">
        <xs:all>
            <xs:element name="any_value" type="xs:string"/>
        </xs:all>
        <xs:attribute name="attribute_uri" type="mio:mID" use="required"/>
    </xs:complexType>

</xs:schema>

=== modicio/modicio/src/main/resources/example_instance.xml
<?xml version="1.0"?>
<Fragment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://modic.io/ns"
          xsi:schemaLocation="http://modic.io/ns modicio_lang.xsd"
          is_open="true"
          running_time="2002-05-30T09:00:00"
          running_id="1"
          is_reference="true"
          variant_id="1"
          variant_name="main"
          variant_time="2023-08-10T09:00:00">

    <Model>
        <Node name="Project" uri="modicio:demo.project" is_abstract="false">
            <Annotation version_time="2023-08-10T09:00:00" version_id="1" variant_time="2023-08-10T09:00:00" variant_id="1"/>
            <Attribute uri="modicio:demo.project.title" name="Title" dType="phrase" />
            <Attribute uri="modicio:demo.project.deadline" name="Deadline" dType="datetime" />
            <AssociationRelation uri="modicio:demo.project.todos" name="Todos"
                target="modicio:demo.todo">
                <Interface>
                    <Point variant_time="2023-08-10T09:00:00" variant_id="1" />
                </Interface>
            </AssociationRelation>
            <Script uri="modicio:demo.myScript1" name="myScript1" action_type="ActionType" resolver="modicio:resolver">
                <any_value>
                    foo script ... a lot of scala code here
                </any_value>
            </Script>
            <Script uri="modicio:demo.myScript2" name="myScript2" action_type="AnotherActionType" resolver="modicio:resolver2">
                <any_value>
                    bar script ... a lot of scala code here
                </any_value>
            </Script>
        </Node>
        <Node name="Todos" uri="modicio:demo.todo" is_abstract="false">
            <Annotation version_time="2023-08-10T09:30:00" version_id="2" variant_time="2023-08-10T09:30:00" variant_id="2"/>
            <Attribute uri="modicio:demo.todo.title" name="Title" dType="string"/>
        </Node>
        <Node name="Epic" uri="modicio:demo.epic" is_abstract="false">
            <Annotation version_time="2023-08-10T09:30:00" version_id="2" variant_time="2023-08-10T09:30:00" variant_id="2"/>
            <Attribute uri="modicio:demo.epic.title" name="Title" dType="string"/>
            <ParentRelation uri="modicio:demo.todo"/>
        </Node>
        <Node name="Issues" uri="modicio:demo.issues" is_abstract="false">
            <Annotation version_time="2023-08-10T09:30:00" version_id="2" variant_time="2023-08-10T09:30:00" variant_id="2"/>
            <Composition uri="modicio:demo..issues.todo" role="role" target="modicio:demo.todo" public="true"/>
        </Node>
    </Model>

    <Instance name="myProject" modelRoot="modicio:demo.project" uri="modicio:instance.myProject">
        <Header></Header>
        <Object instanceOf="modicio:demo.project">
            <AttributeInstance attribute_uri="modicio:demo.project.title">
                <any_value>My Project Title</any_value>
            </AttributeInstance>
            <AttributeInstance attribute_uri="modicio:demo.project.deadline">
                <any_value>My Project Description</any_value>
            </AttributeInstance>
        </Object>
    </Instance>
</Fragment>
